spring:
 logging:
  file: logs/dev_app.log
  pattern:
   console: "%d %-5level %logger : %msg%n"
   file: "%d %-5level [%thread] %logger : %msg%n"
  level:
   org.springframework.web: DEBUG
   com.stackroute.controllers: DEBUG
   org.hibernate: DEBUG
   
 data:
  mongodb:
   authentication-database: admin
   username: root
   password: root123
   database: mongoboot
   port: 27017
   host: localhost

server:
   port: 8092
   
   
